import { defineConfig } from 'vitepress'
// Generated by `pnpm docs:api` (TypeDoc + typedoc-vitepress-theme) before every docs build.
import typedocSidebar from '../api/typedoc-sidebar.json'

const repo = 'https://github.com/adams100111/toolmark'

export default defineConfig({
  title: 'Toolmark',
  description:
    'Registry-first tools for AI agents that operate a web app: declare once, expose to an in-app agent, WebMCP, desktop MCP, tours and tests.',
  lang: 'en-US',
  base: process.env.DOCS_BASE ?? '/toolmark/',
  cleanUrls: true,
  lastUpdated: true,
  // Internal material (plans, specs, roadmap, release evidence, security review) is not published.
  srcExclude: ['superpowers/**', 'ROADMAP.md', 'release/**', 'security/**'],
  // Guides mention local dev-server URLs; they are examples, not links to check.
  ignoreDeadLinks: [/^https?:\/\/(localhost|127\.0\.0\.1)/],
  themeConfig: {
    nav: [
      { text: 'Getting started', link: '/getting-started' },
      { text: 'Concepts', link: '/concepts/registry' },
      { text: 'Guides', link: '/guides/react' },
      { text: 'Reference', link: '/reference/codes' },
      { text: 'API', link: '/api/' },
    ],
    sidebar: [
      { text: 'Getting started', link: '/getting-started' },
      {
        text: 'Concepts',
        items: [
          { text: 'Registry and tools', link: '/concepts/registry' },
          { text: 'Scopes', link: '/concepts/scopes' },
          { text: 'Callers', link: '/concepts/callers' },
          { text: 'Policy', link: '/concepts/policy' },
          { text: 'Confirmation modes', link: '/concepts/confirmation' },
          { text: 'Results', link: '/concepts/results' },
        ],
      },
      {
        text: 'Guides',
        items: [
          { text: 'React', link: '/guides/react' },
          { text: 'Forms, arrays and options', link: '/guides/forms' },
          { text: 'Wizards', link: '/guides/wizards' },
          { text: 'Files', link: '/guides/files' },
          { text: 'DOM forms', link: '/guides/dom' },
          { text: 'Inertia', link: '/guides/inertia' },
          { text: 'Next.js', link: '/guides/nextjs' },
          { text: 'Anchors and state', link: '/guides/anchors' },
          { text: 'Tours', link: '/guides/tours' },
          { text: 'WebMCP', link: '/guides/webmcp' },
          { text: 'Desktop MCP', link: '/guides/mcp' },
          { text: 'OpenTelemetry', link: '/guides/otel' },
          { text: 'Lint and the TypeSafe judge', link: '/guides/lint' },
        ],
      },
      { text: 'Protocol v1', link: '/protocol-v1' },
      { text: 'Laravel reference', link: '/guides/laravel-reference' },
      {
        text: 'Reference',
        items: [{ text: 'Error, refusal and event codes', link: '/reference/codes' }],
      },
      {
        text: 'Policies',
        items: [
          { text: 'Versioning', link: '/policies/versioning' },
          { text: 'Deprecation', link: '/policies/deprecation' },
          { text: 'Tool name stability', link: '/policies/tool-names' },
        ],
      },
      { text: 'API', link: '/api/', collapsed: true, items: typedocSidebar },
    ],
    socialLinks: [{ icon: 'github', link: repo }],
    editLink: { pattern: `${repo}/edit/main/docs/:path` },
    search: { provider: 'local' },
    outline: { level: [2, 3] },
  },
})
