#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s?%s %s [y/N] ' "$YELLOW" "$RESET" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Toolmark 1.0.0 first publish: the owner steps O-a … O-k of
# docs/release/owner-handoff.md, in order. Run from the repo root on `main`:
#   bash scripts/owner-publish-wizard.sh
# Every GitHub change goes through `gh` after a y/N gate; if an API call fails the
# wizard prints the manual UI path instead. Nothing is written to .env: the only
# secret (the npm bootstrap token) goes straight into the npm-release environment.

REPO="adams100111/toolmark"
OWNER_LOGIN="adams100111"
ENV_NAME="npm-release"
# The commit that carries the 1.0.0 versions (PR #6 merge); see owner-handoff.md.
RELEASE_SHA="ffeb8c7667e48fec8a4f7035d828905e6c2e6a24"
PACKAGES=(core react inertia testing tour mcp lint judge-typesafe)
# Jobs that run on every PR (ci.yml + release.yml's release-dry-run); see owner-handoff.md.
REQUIRED_CHECKS=(
  "plan" "lint" "typecheck" "types-ts7" "build" "quality" "docs"
  "unit (node 22, react 19.3.0, inertia 3.7.1)"
  "unit (node 24, react 18.3.1, inertia 2.3.28)"
  "unit (node 24, react 19.3.0, inertia 2.3.28)"
  "unit (node 24, react 19.3.0, inertia 3.7.1)"
  "zod3 (node 24, zod 3.25.76)"
  "browser (chromium)" "browser (firefox)" "browser (webkit)"
  "example-nextjs"
  "example-laravel (bridge-cache database)" "example-laravel (bridge-cache redis)"
  "release-dry-run"
)
# The npm CLI used for `npm trust` (needs npm >= 11.15).
NPM_TRUST=(npx -y npm@12 trust)

# gh_try "what" cmd...: run a gh command; on failure print the manual fallback.
gh_try() {
  local what="$1"; shift
  if "$@" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$what"
  else
    SKIPPED+=("$what")
    warn "could not do it with gh: $what (do it in the browser, see above)"
  fi
}

TOTAL_STAGES=16

banner "Toolmark 1.0.0: first publish to npm"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pre-flight: the right account, repo and commit"
command -v gh >/dev/null 2>&1 || { warn "gh is not installed"; exit 1; }
gh auth status >/dev/null 2>&1 || { warn "run: gh auth login"; exit 1; }
login=$(gh api user -q .login)
[[ "$login" == "$OWNER_LOGIN" ]] || { warn "gh is logged in as $login, expected $OWNER_LOGIN"; exit 1; }
say "gh account: $login"
git fetch -q origin main
MAIN_SHA=$(git rev-parse origin/main)
say "release commit (owner-handoff.md): ${BOLD}${RELEASE_SHA:0:7}${RESET}"
say "origin/main now:                   ${BOLD}${MAIN_SHA:0:7}${RESET}"
git merge-base --is-ancestor "$RELEASE_SHA" "$MAIN_SHA" \
  || { warn "origin/main does not contain the release commit"; exit 1; }
# Commits after the release commit may only touch docs/ or this wizard.
risky=$(git diff --name-only "$RELEASE_SHA" "$MAIN_SHA" | grep -vE '^(docs/|scripts/owner-publish-wizard\.sh$)' || true)
if [[ -n "$risky" ]]; then
  warn "main changed more than docs since the release commit:"
  printf '%s\n' "$risky" | sed 's/^/      /'
  warn "stop and ask for a fresh release check"; exit 1
fi
note "Latest ci.yml runs on main:"
gh run list --repo "$REPO" --workflow ci.yml --branch main --limit 3 \
  --json headSha,conclusion,status -q '.[] | "    \(.headSha[0:7])  \(.status)  \(.conclusion)"' || true
confirm "Is ci.yml green for ${MAIN_SHA:0:7}?" || { warn "stop: wait for green CI"; exit 1; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "O-a · IP and ownership check"
say "Before anything becomes public: confirm you own this code and your employment"
say "IP terms allow publishing it as open source (spec §22)."
note "If this fails, stop here. Nothing below should run."
confirm "IP and ownership confirmed?" || { warn "stopped at O-a"; exit 1; }

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "O-b · npm org 'toolmark' and 2FA"
ask NPM_USER "Your npm username:"
open_url "https://www.npmjs.com/settings/$NPM_USER/tfa"
step "Make sure two-factor authentication is on for your npm account (auth and writes)."
pause "Enter when 2FA is on"
open_url "https://www.npmjs.com/org/create"
step "Create the organization named exactly: toolmark (free plan, public packages)."
step "If it already exists under your account, just confirm."
pause "Enter when https://www.npmjs.com/org/toolmark exists"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "O-c · Make the repository public"
say "Provenance and the required-reviewer gate on $ENV_NAME need a public repo."
warn "This publishes the whole git history of $REPO."
if confirm "Make $REPO public now?"; then
  gh_try "repo visibility → public" gh repo edit "$REPO" --visibility public --accept-visibility-change-consequences
else
  warn "stopping: the release job refuses to publish from a private repo"; exit 1
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "O-d · Actions settings"
say "Workflow token: read-only by default; Actions may create and approve PRs"
say "(changesets opens the 'Version Packages' PR)."
note "Manual path: Settings → Actions → General → Workflow permissions."
if confirm "Apply these Actions settings?"; then
  gh_try "Actions: read-only token, may create/approve PRs" \
    gh api -X PUT "repos/$REPO/actions/permissions/workflow" \
      -f default_workflow_permissions=read -F can_approve_pull_request_reviews=true
fi
open_url "https://github.com/$REPO/settings/actions"
pause "Enter when the page shows 'Read repository contents' + the PR checkbox ticked"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "O-d · Code security"
say "Private vulnerability reporting, Dependabot alerts, secret scanning + push protection."
note "Manual path: Settings → Code security."
if confirm "Enable all four?"; then
  gh_try "private vulnerability reporting" gh api -X PUT "repos/$REPO/private-vulnerability-reporting"
  gh_try "Dependabot alerts" gh api -X PUT "repos/$REPO/vulnerability-alerts"
  gh_try "secret scanning + push protection" gh api -X PATCH "repos/$REPO" --input - <<'JSON'
{"security_and_analysis":{"secret_scanning":{"status":"enabled"},"secret_scanning_push_protection":{"status":"enabled"}}}
JSON
fi
open_url "https://github.com/$REPO/settings/security_analysis"
pause "Enter when all four show as enabled"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "O-d · GitHub Pages and the docs site"
note "Manual path: Settings → Pages → Source: GitHub Actions."
if confirm "Set the Pages source to GitHub Actions and deploy the docs?"; then
  gh api -X POST "repos/$REPO/pages" -f build_type=workflow >/dev/null 2>&1 \
    || gh_try "Pages source → GitHub Actions" gh api -X PUT "repos/$REPO/pages" -f build_type=workflow
  gh_try "docs-deploy.yml dispatched" gh workflow run docs-deploy.yml --repo "$REPO" --ref main
fi
open_url "https://github.com/$REPO/settings/pages"
note "The site will be at https://adams100111.github.io/toolmark/ once docs-deploy finishes."
pause "Enter to continue (no need to wait for the deploy)"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "O-f · The $ENV_NAME environment"
say "Required reviewer: you only (self-review allowed: you push the release commit)."
say "Deployment branches: main only."
note "Manual path: Settings → Environments → $ENV_NAME."
if confirm "Create/update $ENV_NAME like that?"; then
  uid=$(gh api user -q .id)
  gh_try "$ENV_NAME: reviewer $OWNER_LOGIN, custom branch policy" \
    gh api -X PUT "repos/$REPO/environments/$ENV_NAME" --input - <<JSON
{"prevent_self_review":false,"reviewers":[{"type":"User","id":$uid}],
 "deployment_branch_policy":{"protected_branches":false,"custom_branch_policies":true}}
JSON
  if gh api "repos/$REPO/environments/$ENV_NAME/deployment-branch-policies" \
       -q '.branch_policies[].name' 2>/dev/null | grep -qx main; then
    printf '  %s✓%s branch policy main already present\n' "$GREEN" "$RESET"
  else
    gh_try "$ENV_NAME: deploy from main only" \
      gh api -X POST "repos/$REPO/environments/$ENV_NAME/deployment-branch-policies" -f name=main -f type=branch
  fi
fi
open_url "https://github.com/$REPO/settings/environments"
step "Check: Required reviewers = $OWNER_LOGIN; 'Prevent self-review' OFF; branches = main."
pause "Enter when it looks right"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "O-e · Branch protection on main"
say "Require PRs, block force-pushes, and require these ${#REQUIRED_CHECKS[@]} checks:"
for c in "${REQUIRED_CHECKS[@]}"; do note "  $c"; done
if confirm "Apply this protection to main?"; then
  checks_json=$(printf '%s\n' "${REQUIRED_CHECKS[@]}" | python3 -c 'import json,sys;print(json.dumps([l.rstrip("\n") for l in sys.stdin if l.strip()]))')
  gh_try "main: PRs required, ${#REQUIRED_CHECKS[@]} checks, no force-push" \
    gh api -X PUT "repos/$REPO/branches/main/protection" --input - <<JSON
{"required_status_checks":{"strict":false,"contexts":$checks_json},
 "enforce_admins":false,
 "required_pull_request_reviews":{"required_approving_review_count":0},
 "restrictions":null,
 "allow_force_pushes":false,"allow_deletions":false}
JSON
fi
open_url "https://github.com/$REPO/settings/branches"
pause "Enter to continue"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "O-g · Bootstrap npm token (one publish only)"
open_url "https://www.npmjs.com/settings/$NPM_USER/tokens/granular-access-tokens/new"
step "Name: toolmark-bootstrap-1.0.0"
step "Expiration: the shortest available."
step "Packages and scopes: Read and write → scope @toolmark (all packages)."
step "Tick 'Bypass two-factor authentication (2FA)'."
step "Generate, then copy the token (shown once)."
ask_secret NPM_BOOTSTRAP_TOKEN "Paste the token (hidden):"
[[ -n "${NPM_BOOTSTRAP_TOKEN:-}" ]] || { warn "no token entered"; exit 1; }
if printf '%s' "$NPM_BOOTSTRAP_TOKEN" | gh secret set NPM_BOOTSTRAP_TOKEN --env "$ENV_NAME" --repo "$REPO" >/dev/null 2>&1; then
  WRITTEN_SECRET+=("NPM_BOOTSTRAP_TOKEN ($ENV_NAME environment)")
  printf '  %s✓ set%s environment secret NPM_BOOTSTRAP_TOKEN on %s\n' "$GREEN" "$RESET" "$ENV_NAME"
else
  SKIPPED+=("gh secret set NPM_BOOTSTRAP_TOKEN --env $ENV_NAME --repo $REPO")
  warn "could not set the secret; run the command above by hand"
fi
unset NPM_BOOTSTRAP_TOKEN

# ── 11 ────────────────────────────────────────────────────────────────────
stage "O-h · Enable publishing"
say "Sets the repo variable TOOLMARK_PUBLISH_ENABLED=true (the publish job's on-switch)."
if confirm "Enable publishing?"; then
  gh_try "variable TOOLMARK_PUBLISH_ENABLED=true" \
    gh variable set TOOLMARK_PUBLISH_ENABLED --body true --repo "$REPO"
fi

# ── 12 ────────────────────────────────────────────────────────────────────
stage "O-i · Publish 1.0.0"
warn "This is the irreversible step: npm versions can never be reused."
confirm "Dispatch release.yml on main (${MAIN_SHA:0:7}) now?" || { warn "stopped before publishing"; exit 1; }
gh workflow run release.yml --repo "$REPO" --ref main
sleep 5
run_url=$(gh run list --repo "$REPO" --workflow release.yml --event workflow_dispatch --limit 1 --json url -q '.[0].url')
open_url "$run_url"
step "Check the run is on ${MAIN_SHA:0:7} (shown at the top of the run)."
step "Wait for 'pack' to finish, then 'Review deployments' → tick $ENV_NAME → Approve."
note "If publish fails part-way: 'Re-run failed jobs' on this same run, never a new dispatch."
pause "Enter when the publish job is green"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Check the packages on npm"
ok=0
for p in "${PACKAGES[@]}"; do
  v=$(npm view "@toolmark/$p@1.0.0" version 2>/dev/null || true)
  prov=$(npm view "@toolmark/$p@1.0.0" dist.attestations.provenance.predicateType 2>/dev/null || true)
  if [[ "$v" == "1.0.0" ]]; then ok=$((ok + 1)); printf '  %s✓%s @toolmark/%s@1.0.0  %s\n' "$GREEN" "$RESET" "$p" "${prov:-(no provenance?)}"
  else printf '  %s✗%s @toolmark/%s@1.0.0 not found yet\n' "$RED" "$RESET" "$p"; fi
done
(( ok == ${#PACKAGES[@]} )) || warn "not all 8 are visible yet; npm can lag a minute. Re-check before going on."
pause "Enter when all 8 show 1.0.0"

# ── 14 ────────────────────────────────────────────────────────────────────
stage "O-j · Trusted publishing (no more tokens)"
say "Links each package to release.yml + $ENV_NAME, so later releases use OIDC."
"${NPM_TRUST[@]}" github --help >/dev/null 2>&1 || warn "npm trust unavailable; install npm >= 11.15"
step "Log in to npm first if needed (a browser/OTP prompt may appear)."
npx -y npm@12 whoami >/dev/null 2>&1 || npx -y npm@12 login
for p in "${PACKAGES[@]}"; do
  if "${NPM_TRUST[@]}" github "@toolmark/$p" --file release.yml --repo "$REPO" --env "$ENV_NAME" --allow-publish --yes; then
    printf '  %s✓%s trusted publisher for @toolmark/%s\n' "$GREEN" "$RESET" "$p"
  else
    SKIPPED+=("npm trust github @toolmark/$p --file release.yml --repo $REPO --env $ENV_NAME --allow-publish")
    warn "failed for @toolmark/$p (retry it by hand)"
  fi
done
pause "Enter to continue"

# ── 15 ────────────────────────────────────────────────────────────────────
stage "O-k · Revoke the bootstrap token"
gh_try "deleted environment secret NPM_BOOTSTRAP_TOKEN" \
  gh secret delete NPM_BOOTSTRAP_TOKEN --env "$ENV_NAME" --repo "$REPO"
open_url "https://www.npmjs.com/settings/$NPM_USER/tokens"
step "Delete the token 'toolmark-bootstrap-1.0.0'."
note "Optional hardening, per package: Settings → Publishing access →"
note "'Require two-factor authentication and disallow tokens'."
pause "Enter when the token is revoked"

# ── 16 ────────────────────────────────────────────────────────────────────
stage "Hand back"
say "Toolmark 1.0.0 is on npm. Tell Claude in the toolmark session:"
printf '\n    %s1.0.0 published%s\n\n' "$BOLD" "$RESET"
note "It then runs Task 7d: npm audit signatures, tags and releases, docs site,"
note "spec-watch going live, and the final roadmap update."
pause "Enter to finish"

finish
